steps:
- name: maven:3-eclipse-temurin-17-alpine
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/august-enigma-362212/brainlinks-docker/helloservice', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/august-enigma-362212/brainlinks-docker/helloservice']
options:
  logging: CLOUD_LOGGING_ONLY
images: ["us-central1-docker.pkg.dev/august-enigma-362212/brainlinks-docker/helloservice"]
