steps:
- name: maven:3-eclipse-temurin-17-alpine
  entrypoint: mvn
  args: ["package", "-Dmaven.test.skip=true"]
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/august-enigma-362212/helloservice', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/august-enigma-362212/brainlinks-docker/helloservice']
images:
- gcr.io/august-enigma-362212/helloservice
options:
  logging: CLOUD_LOGGING_ONLY
